/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * parker-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary 帶共享密鑰打 apps/eve 的 /ping，驗證 parker-api → eve 認證機制（票 17 walking skeleton）
 */
export const getApiV1DebugEvePingResponse = zod.object({
  "ok": zod.boolean(),
  "status": zod.number()
})

