/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * parker-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Google OAuth callback: finds/creates the Player, checks <app>.access, redirects back to the app's URL with tokens
 */
export const getApiV1AuthGoogleCallbackQueryParams = zod.object({
  "code": zod.string().optional(),
  "state": zod.string().optional(),
  "error": zod.string().optional()
})

/**
 * @summary Exchange a refresh token for a new access token
 */
export const postApiV1AuthRefreshBody = zod.object({
  "refreshToken": zod.string()
})

export const postApiV1AuthRefreshResponse = zod.object({
  "accessToken": zod.string()
})

