/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * parker-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a cat (caller Player becomes its first member)
 */



export const postApiV1CatCareCatsBody = zod.object({
  "name": zod.string().min(1),
  "birthdate": zod.string().optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List cats the caller Player belongs to
 */
export const getApiV1CatCareCatsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsResponse = zod.array(getApiV1CatCareCatsResponseItem)

/**
 * @summary Get a single cat (caller must be a member)
 */
export const getApiV1CatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Update a cat's basic profile (name/birthdate/notes; caller must be a member)
 */
export const patchApiV1CatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})




export const patchApiV1CatCareCatsCatIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "birthdate": zod.string().date().optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Archive a cat (soft delete; caller must be a member)
 */
export const deleteApiV1CatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})

export const deleteApiV1CatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Record a bowel movement for a cat
 */
export const postApiV1CatCareCatsCatIdBowelMovementsParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdBowelMovementsBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).optional(),
  "isAbnormal": zod.boolean().optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List bowel movement history for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdBowelMovementsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdBowelMovementsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdBowelMovementsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).nullish(),
  "isAbnormal": zod.boolean(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsCatIdBowelMovementsResponse = zod.array(getApiV1CatCareCatsCatIdBowelMovementsResponseItem)

/**
 * @summary Edit a bowel movement record (only the recording Player may edit)
 */
export const patchApiV1CatCareCatsCatIdBowelMovementsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

export const patchApiV1CatCareCatsCatIdBowelMovementsIdBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).optional(),
  "isAbnormal": zod.boolean().optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdBowelMovementsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).nullish(),
  "isAbnormal": zod.boolean(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Hard-delete a bowel movement record (only the recording Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdBowelMovementsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary Record a weight measurement for a cat
 */
export const postApiV1CatCareCatsCatIdWeightRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdWeightRecordsBodyWeightGramsMin = 0;



export const postApiV1CatCareCatsCatIdWeightRecordsBody = zod.object({
  "measuredAt": zod.string().datetime({}).optional(),
  "weightGrams": zod.number().min(postApiV1CatCareCatsCatIdWeightRecordsBodyWeightGramsMin),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List weight history for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdWeightRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdWeightRecordsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdWeightRecordsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "measuredBy": zod.string().uuid(),
  "measuredAt": zod.string(),
  "weightGrams": zod.number(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsCatIdWeightRecordsResponse = zod.array(getApiV1CatCareCatsCatIdWeightRecordsResponseItem)

/**
 * @summary Edit a weight record (only the measuring Player may edit)
 */
export const patchApiV1CatCareCatsCatIdWeightRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

export const patchApiV1CatCareCatsCatIdWeightRecordsIdBodyWeightGramsMin = 0;



export const patchApiV1CatCareCatsCatIdWeightRecordsIdBody = zod.object({
  "measuredAt": zod.string().datetime({}).optional(),
  "weightGrams": zod.number().min(patchApiV1CatCareCatsCatIdWeightRecordsIdBodyWeightGramsMin).optional(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdWeightRecordsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "measuredBy": zod.string().uuid(),
  "measuredAt": zod.string(),
  "weightGrams": zod.number(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Hard-delete a weight record (only the measuring Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdWeightRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary Record a subcutaneous fluid injection for a cat
 */
export const postApiV1CatCareCatsCatIdFluidInjectionsParams = zod.object({
  "catId": zod.string().uuid()
})


export const postApiV1CatCareCatsCatIdFluidInjectionsBodyVolumeMlMin = 0;




export const postApiV1CatCareCatsCatIdFluidInjectionsBody = zod.object({
  "injectedAt": zod.string().datetime({}).optional(),
  "site": zod.enum(['left', 'right', 'nape', 'other']),
  "siteOther": zod.string().min(1).optional(),
  "volumeMl": zod.number().min(postApiV1CatCareCatsCatIdFluidInjectionsBodyVolumeMlMin),
  "fluidType": zod.enum(['normalSaline', 'lactatedRingers', 'other']),
  "fluidTypeOther": zod.string().min(1).optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List fluid injection history for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdFluidInjectionsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdFluidInjectionsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdFluidInjectionsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "injectedBy": zod.string().uuid(),
  "injectedAt": zod.string(),
  "site": zod.enum(['left', 'right', 'nape', 'other']),
  "siteOther": zod.string().nullish(),
  "volumeMl": zod.number(),
  "fluidType": zod.enum(['normalSaline', 'lactatedRingers', 'other']),
  "fluidTypeOther": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsCatIdFluidInjectionsResponse = zod.array(getApiV1CatCareCatsCatIdFluidInjectionsResponseItem)

/**
 * @summary Edit a fluid injection record (only the injecting Player may edit)
 */
export const patchApiV1CatCareCatsCatIdFluidInjectionsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})


export const patchApiV1CatCareCatsCatIdFluidInjectionsIdBodyVolumeMlMin = 0;




export const patchApiV1CatCareCatsCatIdFluidInjectionsIdBody = zod.object({
  "injectedAt": zod.string().datetime({}).optional(),
  "site": zod.enum(['left', 'right', 'nape', 'other']).optional(),
  "siteOther": zod.string().min(1).optional(),
  "volumeMl": zod.number().min(patchApiV1CatCareCatsCatIdFluidInjectionsIdBodyVolumeMlMin).optional(),
  "fluidType": zod.enum(['normalSaline', 'lactatedRingers', 'other']).optional(),
  "fluidTypeOther": zod.string().min(1).optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdFluidInjectionsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "injectedBy": zod.string().uuid(),
  "injectedAt": zod.string(),
  "site": zod.enum(['left', 'right', 'nape', 'other']),
  "siteOther": zod.string().nullish(),
  "volumeMl": zod.number(),
  "fluidType": zod.enum(['normalSaline', 'lactatedRingers', 'other']),
  "fluidTypeOther": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Hard-delete a fluid injection record (only the injecting Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdFluidInjectionsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary Manually record a bloodwork report for a cat (always created as confirmed)
 */
export const postApiV1CatCareCatsCatIdBloodworkRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdBloodworkRecordsBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "glu": zod.number().nullish(),
  "crea": zod.number().nullish(),
  "bun": zod.number().nullish(),
  "bunCrea": zod.number().nullish(),
  "tp": zod.number().nullish(),
  "alb": zod.number().nullish(),
  "glob": zod.number().nullish(),
  "albGlob": zod.number().nullish(),
  "alt": zod.number().nullish(),
  "alkp": zod.number().nullish(),
  "fpl": zod.number().nullish(),
  "na": zod.number().nullish(),
  "k": zod.number().nullish(),
  "naK": zod.number().nullish(),
  "cl": zod.number().nullish(),
  "osmCalc": zod.number().nullish(),
  "tt4": zod.number().nullish(),
  "wbc": zod.number().nullish(),
  "lym": zod.number().nullish(),
  "mono": zod.number().nullish(),
  "gran": zod.number().nullish(),
  "lymPercent": zod.number().nullish(),
  "monPercent": zod.number().nullish(),
  "graPercent": zod.number().nullish(),
  "hgb": zod.number().nullish(),
  "hct": zod.number().nullish(),
  "rbc": zod.number().nullish(),
  "mcv": zod.number().nullish(),
  "mch": zod.number().nullish(),
  "mchc": zod.number().nullish(),
  "rdwPercent": zod.number().nullish(),
  "rdwa": zod.number().nullish(),
  "plt": zod.number().nullish(),
  "mpv": zod.number().nullish()
})

/**
 * @summary List bloodwork records for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdBloodworkRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdBloodworkRecordsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdBloodworkRecordsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "status": zod.enum(['draft', 'confirmed']),
  "createdAt": zod.string(),
  "glu": zod.number().nullish(),
  "crea": zod.number().nullish(),
  "bun": zod.number().nullish(),
  "bunCrea": zod.number().nullish(),
  "tp": zod.number().nullish(),
  "alb": zod.number().nullish(),
  "glob": zod.number().nullish(),
  "albGlob": zod.number().nullish(),
  "alt": zod.number().nullish(),
  "alkp": zod.number().nullish(),
  "fpl": zod.number().nullish(),
  "na": zod.number().nullish(),
  "k": zod.number().nullish(),
  "naK": zod.number().nullish(),
  "cl": zod.number().nullish(),
  "osmCalc": zod.number().nullish(),
  "tt4": zod.number().nullish(),
  "wbc": zod.number().nullish(),
  "lym": zod.number().nullish(),
  "mono": zod.number().nullish(),
  "gran": zod.number().nullish(),
  "lymPercent": zod.number().nullish(),
  "monPercent": zod.number().nullish(),
  "graPercent": zod.number().nullish(),
  "hgb": zod.number().nullish(),
  "hct": zod.number().nullish(),
  "rbc": zod.number().nullish(),
  "mcv": zod.number().nullish(),
  "mch": zod.number().nullish(),
  "mchc": zod.number().nullish(),
  "rdwPercent": zod.number().nullish(),
  "rdwa": zod.number().nullish(),
  "plt": zod.number().nullish(),
  "mpv": zod.number().nullish()
})
export const getApiV1CatCareCatsCatIdBloodworkRecordsResponse = zod.array(getApiV1CatCareCatsCatIdBloodworkRecordsResponseItem)

/**
 * @summary Edit a bloodwork record's fields (only the recording Player may edit)
 */
export const patchApiV1CatCareCatsCatIdBloodworkRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

export const patchApiV1CatCareCatsCatIdBloodworkRecordsIdBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "glu": zod.number().nullish(),
  "crea": zod.number().nullish(),
  "bun": zod.number().nullish(),
  "bunCrea": zod.number().nullish(),
  "tp": zod.number().nullish(),
  "alb": zod.number().nullish(),
  "glob": zod.number().nullish(),
  "albGlob": zod.number().nullish(),
  "alt": zod.number().nullish(),
  "alkp": zod.number().nullish(),
  "fpl": zod.number().nullish(),
  "na": zod.number().nullish(),
  "k": zod.number().nullish(),
  "naK": zod.number().nullish(),
  "cl": zod.number().nullish(),
  "osmCalc": zod.number().nullish(),
  "tt4": zod.number().nullish(),
  "wbc": zod.number().nullish(),
  "lym": zod.number().nullish(),
  "mono": zod.number().nullish(),
  "gran": zod.number().nullish(),
  "lymPercent": zod.number().nullish(),
  "monPercent": zod.number().nullish(),
  "graPercent": zod.number().nullish(),
  "hgb": zod.number().nullish(),
  "hct": zod.number().nullish(),
  "rbc": zod.number().nullish(),
  "mcv": zod.number().nullish(),
  "mch": zod.number().nullish(),
  "mchc": zod.number().nullish(),
  "rdwPercent": zod.number().nullish(),
  "rdwa": zod.number().nullish(),
  "plt": zod.number().nullish(),
  "mpv": zod.number().nullish(),
  "status": zod.enum(['confirmed']).optional()
})

export const patchApiV1CatCareCatsCatIdBloodworkRecordsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "status": zod.enum(['draft', 'confirmed']),
  "createdAt": zod.string(),
  "glu": zod.number().nullish(),
  "crea": zod.number().nullish(),
  "bun": zod.number().nullish(),
  "bunCrea": zod.number().nullish(),
  "tp": zod.number().nullish(),
  "alb": zod.number().nullish(),
  "glob": zod.number().nullish(),
  "albGlob": zod.number().nullish(),
  "alt": zod.number().nullish(),
  "alkp": zod.number().nullish(),
  "fpl": zod.number().nullish(),
  "na": zod.number().nullish(),
  "k": zod.number().nullish(),
  "naK": zod.number().nullish(),
  "cl": zod.number().nullish(),
  "osmCalc": zod.number().nullish(),
  "tt4": zod.number().nullish(),
  "wbc": zod.number().nullish(),
  "lym": zod.number().nullish(),
  "mono": zod.number().nullish(),
  "gran": zod.number().nullish(),
  "lymPercent": zod.number().nullish(),
  "monPercent": zod.number().nullish(),
  "graPercent": zod.number().nullish(),
  "hgb": zod.number().nullish(),
  "hct": zod.number().nullish(),
  "rbc": zod.number().nullish(),
  "mcv": zod.number().nullish(),
  "mch": zod.number().nullish(),
  "mchc": zod.number().nullish(),
  "rdwPercent": zod.number().nullish(),
  "rdwa": zod.number().nullish(),
  "plt": zod.number().nullish(),
  "mpv": zod.number().nullish()
})

/**
 * @summary Hard-delete a bloodwork record (only the recording Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdBloodworkRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary Upload a bloodwork report photo for AI recognition (async; result lands as a draft record once eve calls back)
 */
export const postApiV1CatCareCatsCatIdBloodworkRecordsRecognizeParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdBloodworkRecordsRecognizeBody = zod.object({
  "photo": zod.instanceof(File)
})

/**
 * @summary eve → parker-api callback for a photo-recognition job (service-to-service; verified by shared key, not Player auth)
 */
export const postApiV1CatCareEveCallbackBloodworkRecognitionJobIdParams = zod.object({
  "jobId": zod.string()
})

export const postApiV1CatCareEveCallbackBloodworkRecognitionJobIdBody = zod.union([zod.object({
  "status": zod.enum(['success']),
  "data": zod.object({
  "glu": zod.number().nullish(),
  "crea": zod.number().nullish(),
  "bun": zod.number().nullish(),
  "bunCrea": zod.number().nullish(),
  "tp": zod.number().nullish(),
  "alb": zod.number().nullish(),
  "glob": zod.number().nullish(),
  "albGlob": zod.number().nullish(),
  "alt": zod.number().nullish(),
  "alkp": zod.number().nullish(),
  "fpl": zod.number().nullish(),
  "na": zod.number().nullish(),
  "k": zod.number().nullish(),
  "naK": zod.number().nullish(),
  "cl": zod.number().nullish(),
  "osmCalc": zod.number().nullish(),
  "tt4": zod.number().nullish(),
  "wbc": zod.number().nullish(),
  "lym": zod.number().nullish(),
  "mono": zod.number().nullish(),
  "gran": zod.number().nullish(),
  "lymPercent": zod.number().nullish(),
  "monPercent": zod.number().nullish(),
  "graPercent": zod.number().nullish(),
  "hgb": zod.number().nullish(),
  "hct": zod.number().nullish(),
  "rbc": zod.number().nullish(),
  "mcv": zod.number().nullish(),
  "mch": zod.number().nullish(),
  "mchc": zod.number().nullish(),
  "rdwPercent": zod.number().nullish(),
  "rdwa": zod.number().nullish(),
  "plt": zod.number().nullish(),
  "mpv": zod.number().nullish()
})
}),zod.object({
  "status": zod.enum(['failed'])
})])

export const postApiV1CatCareEveCallbackBloodworkRecognitionJobIdResponse = zod.object({
  "ok": zod.boolean()
})

/**
 * @summary List the Players (co-caretakers) currently on a cat (caller must be a member)
 */
export const getApiV1CatCareCatsCatIdPlayersParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdPlayersResponseItem = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string()
})
export const getApiV1CatCareCatsCatIdPlayersResponse = zod.array(getApiV1CatCareCatsCatIdPlayersResponseItem)

/**
 * @summary Invite an existing Player (by email) to join a cat (caller must be a member)
 */
export const postApiV1CatCareCatsCatIdPlayersParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdPlayersBody = zod.object({
  "email": zod.string().email()
})

/**
 * @summary Leave a cat (caller only; the chip-registration custodian must transfer first)
 */
export const deleteApiV1CatCareCatsCatIdPlayersMeParams = zod.object({
  "catId": zod.string().uuid()
})

/**
 * @summary Set or transfer the chip-registration custodian (target must already be a member)
 */
export const putApiV1CatCareCatsCatIdChipPlayerParams = zod.object({
  "catId": zod.string().uuid()
})

export const putApiV1CatCareCatsCatIdChipPlayerBody = zod.object({
  "email": zod.string().email()
})

export const putApiV1CatCareCatsCatIdChipPlayerResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

