/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * parker-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a cat (caller Player becomes its first member)
 */



export const postApiV1CatCareCatsBody = zod.object({
  "name": zod.string().min(1),
  "birthdate": zod.string().optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List cats the caller Player belongs to
 */
export const getApiV1CatCareCatsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsResponse = zod.array(getApiV1CatCareCatsResponseItem)

/**
 * @summary Get a single cat (caller must be a member)
 */
export const getApiV1CatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Archive a cat (soft delete; caller must be a member)
 */
export const deleteApiV1CatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})

export const deleteApiV1CatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Record a bowel movement for a cat
 */
export const postApiV1CatCareCatsCatIdBowelMovementsParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdBowelMovementsBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).optional(),
  "isAbnormal": zod.boolean().optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List bowel movement history for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdBowelMovementsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdBowelMovementsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdBowelMovementsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).nullish(),
  "isAbnormal": zod.boolean(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsCatIdBowelMovementsResponse = zod.array(getApiV1CatCareCatsCatIdBowelMovementsResponseItem)

/**
 * @summary Edit a bowel movement record (only the recording Player may edit)
 */
export const patchApiV1CatCareCatsCatIdBowelMovementsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

export const patchApiV1CatCareCatsCatIdBowelMovementsIdBody = zod.object({
  "recordedAt": zod.string().datetime({}).optional(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).optional(),
  "isAbnormal": zod.boolean().optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdBowelMovementsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "stoolType": zod.enum(['normal', 'hard', 'soft', 'watery', 'bloody', 'mucous']).nullish(),
  "isAbnormal": zod.boolean(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Hard-delete a bowel movement record (only the recording Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdBowelMovementsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary Record a weight measurement for a cat
 */
export const postApiV1CatCareCatsCatIdWeightRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdWeightRecordsBodyWeightGramsMin = 0;



export const postApiV1CatCareCatsCatIdWeightRecordsBody = zod.object({
  "measuredAt": zod.string().datetime({}).optional(),
  "weightGrams": zod.number().min(postApiV1CatCareCatsCatIdWeightRecordsBodyWeightGramsMin),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).optional(),
  "notes": zod.string().optional()
})

/**
 * @summary List weight history for a cat (optionally filtered by ?from=&to= date range)
 */
export const getApiV1CatCareCatsCatIdWeightRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdWeightRecordsQueryParams = zod.object({
  "from": zod.string().date().optional(),
  "to": zod.string().date().optional()
})

export const getApiV1CatCareCatsCatIdWeightRecordsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "measuredBy": zod.string().uuid(),
  "measuredAt": zod.string(),
  "weightGrams": zod.number(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1CatCareCatsCatIdWeightRecordsResponse = zod.array(getApiV1CatCareCatsCatIdWeightRecordsResponseItem)

/**
 * @summary Edit a weight record (only the measuring Player may edit)
 */
export const patchApiV1CatCareCatsCatIdWeightRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

export const patchApiV1CatCareCatsCatIdWeightRecordsIdBodyWeightGramsMin = 0;



export const patchApiV1CatCareCatsCatIdWeightRecordsIdBody = zod.object({
  "measuredAt": zod.string().datetime({}).optional(),
  "weightGrams": zod.number().min(patchApiV1CatCareCatsCatIdWeightRecordsIdBodyWeightGramsMin).optional(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).optional(),
  "notes": zod.string().optional()
})

export const patchApiV1CatCareCatsCatIdWeightRecordsIdResponse = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "measuredBy": zod.string().uuid(),
  "measuredAt": zod.string(),
  "weightGrams": zod.number(),
  "method": zod.enum(['catScale', 'holdAndSubtract', 'other']).nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Hard-delete a weight record (only the measuring Player may delete)
 */
export const deleteApiV1CatCareCatsCatIdWeightRecordsIdParams = zod.object({
  "catId": zod.string().uuid(),
  "id": zod.string().uuid()
})

/**
 * @summary List the Players (co-caretakers) currently on a cat (caller must be a member)
 */
export const getApiV1CatCareCatsCatIdPlayersParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1CatCareCatsCatIdPlayersResponseItem = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string()
})
export const getApiV1CatCareCatsCatIdPlayersResponse = zod.array(getApiV1CatCareCatsCatIdPlayersResponseItem)

/**
 * @summary Invite an existing Player (by email) to join a cat (caller must be a member)
 */
export const postApiV1CatCareCatsCatIdPlayersParams = zod.object({
  "catId": zod.string().uuid()
})

export const postApiV1CatCareCatsCatIdPlayersBody = zod.object({
  "email": zod.string().email()
})

/**
 * @summary Leave a cat (caller only; the chip-registration custodian must transfer first)
 */
export const deleteApiV1CatCareCatsCatIdPlayersMeParams = zod.object({
  "catId": zod.string().uuid()
})

/**
 * @summary Set or transfer the chip-registration custodian (target must already be a member)
 */
export const putApiV1CatCareCatsCatIdChipPlayerParams = zod.object({
  "catId": zod.string().uuid()
})

export const putApiV1CatCareCatsCatIdChipPlayerBody = zod.object({
  "email": zod.string().email()
})

export const putApiV1CatCareCatsCatIdChipPlayerResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

