/**
 * Multi-cat switcher stub (issue #4: dropdown, not tabs — mobile width can't fit many
 * tabs). Wired to a placeholder single entry for now; a later agent should swap the
 * static `cats` array for a real TanStack Query hook (e.g. `useListCats()` once
 * generated by orval) and add an onChange that updates whatever "current cat" seam
 * the feature pages end up using.
 */
export function CatSwitcher() {
  const cats = [{ id: 'placeholder', name: '我的貓咪' }];
  const current = cats[0];

  return (
    <select
      aria-label="切換貓咪"
      defaultValue={current.id}
      disabled={cats.length <= 1}
      className="max-w-[45vw] truncate bg-transparent text-base font-semibold text-gray-900 disabled:opacity-100"
    >
      {cats.map((cat) => (
        <option key={cat.id} value={cat.id}>
          {cat.name}
        </option>
      ))}
    </select>
  );
}
