/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * parker-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Google OAuth callback: redirects to Admin Dashboard with a pending userId, or a one-time exchange code (ADR-0008)
 */
export const getApiV1AdminLoginGoogleCallbackQueryParams = zod.object({
  "code": zod.string().optional(),
  "state": zod.string().optional()
})

/**
 * @summary Exchange a one-time login code (from the OAuth callback redirect) for real access/refresh tokens (ADR-0008)
 */
export const postApiV1AdminLoginExchangeBody = zod.object({
  "code": zod.string()
})

export const postApiV1AdminLoginExchangeResponse = zod.object({
  "accessToken": zod.string(),
  "refreshToken": zod.string(),
  "user": zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['pending', 'approved', 'rejected'])
})
})

/**
 * @summary Exchange a refresh token for a new access token
 */
export const postApiV1AdminRefreshBody = zod.object({
  "refreshToken": zod.string()
})

export const postApiV1AdminRefreshResponse = zod.object({
  "accessToken": zod.string()
})

/**
 * @summary Approve a pending User application and assign a Role (requires admin.users.approve)
 */
export const postApiV1AdminUsersIdApproveParams = zod.object({
  "id": zod.string().uuid()
})

export const postApiV1AdminUsersIdApproveBody = zod.object({
  "roleName": zod.enum(['Owner', 'SuperAdmin', 'Viewer'])
})

export const postApiV1AdminUsersIdApproveResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['pending', 'approved', 'rejected'])
})

/**
 * @summary List Users, optionally filtered by status (requires admin.users.view)
 */
export const getApiV1AdminUsersQueryParams = zod.object({
  "status": zod.enum(['pending', 'approved', 'rejected']).optional()
})

export const getApiV1AdminUsersResponseItem = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['pending', 'approved', 'rejected'])
})
export const getApiV1AdminUsersResponse = zod.array(getApiV1AdminUsersResponseItem)

/**
 * @summary Adjust an existing User's Role (requires admin.users.approve)
 */
export const patchApiV1AdminUsersIdRoleParams = zod.object({
  "id": zod.string().uuid()
})

export const patchApiV1AdminUsersIdRoleBody = zod.object({
  "roleName": zod.enum(['Owner', 'SuperAdmin', 'Viewer'])
})

export const patchApiV1AdminUsersIdRoleResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['pending', 'approved', 'rejected'])
})

/**
 * @summary Reject a pending User application (requires admin.users.approve)
 */
export const postApiV1AdminUsersIdRejectParams = zod.object({
  "id": zod.string().uuid()
})

export const postApiV1AdminUsersIdRejectResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "status": zod.enum(['pending', 'approved', 'rejected'])
})

/**
 * @summary Gateway: list all cats across every Player (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCareCatsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})
export const getApiV1AdminCatCareCatsResponse = zod.array(getApiV1AdminCatCareCatsResponseItem)

/**
 * @summary Gateway: get a single cat's detail (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCareCatsCatIdParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1AdminCatCareCatsCatIdResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
})

/**
 * @summary Gateway: a cat's bowel movement history (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCareCatsCatIdBowelMovementsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1AdminCatCareCatsCatIdBowelMovementsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "recordedBy": zod.string().uuid(),
  "recordedAt": zod.string(),
  "stoolType": zod.string().nullish(),
  "isAbnormal": zod.boolean(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1AdminCatCareCatsCatIdBowelMovementsResponse = zod.array(getApiV1AdminCatCareCatsCatIdBowelMovementsResponseItem)

/**
 * @summary Gateway: a cat's weight history (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCareCatsCatIdWeightRecordsParams = zod.object({
  "catId": zod.string().uuid()
})

export const getApiV1AdminCatCareCatsCatIdWeightRecordsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "catId": zod.string().uuid(),
  "measuredBy": zod.string().uuid(),
  "measuredAt": zod.string(),
  "weightGrams": zod.number(),
  "method": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "createdAt": zod.string()
})
export const getApiV1AdminCatCareCatsCatIdWeightRecordsResponse = zod.array(getApiV1AdminCatCareCatsCatIdWeightRecordsResponseItem)

/**
 * @summary Gateway: Players related to cat-care (have catCare.access or belong to a cat), with profile (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCarePlayersResponseItem = zod.object({
  "player": zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish()
}),
  "cats": zod.array(zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
}))
})
export const getApiV1AdminCatCarePlayersResponse = zod.array(getApiV1AdminCatCarePlayersResponseItem)

/**
 * @summary Gateway: a single cat-care-related Player's detail (requires admin.catCare.viewAll)
 */
export const getApiV1AdminCatCarePlayersPlayerIdParams = zod.object({
  "playerId": zod.string().uuid()
})

export const getApiV1AdminCatCarePlayersPlayerIdResponse = zod.object({
  "player": zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "name": zod.string(),
  "avatarUrl": zod.string().nullish()
}),
  "cats": zod.array(zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "birthdate": zod.string().nullish(),
  "notes": zod.string().nullish(),
  "archivedAt": zod.string().nullish(),
  "chipPlayerId": zod.string().uuid().nullish(),
  "createdAt": zod.string()
}))
})

/**
 * @summary List all Roles (requires rbac.roles.manage)
 */
export const getApiV1AdminRolesResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "createdAt": zod.string()
})
export const getApiV1AdminRolesResponse = zod.array(getApiV1AdminRolesResponseItem)

/**
 * @summary Create a Role (requires rbac.roles.manage)
 */



export const postApiV1AdminRolesBody = zod.object({
  "name": zod.string().min(1)
})

/**
 * @summary Delete a Role (requires rbac.roles.manage)
 */
export const deleteApiV1AdminRolesRoleIdParams = zod.object({
  "roleId": zod.string().uuid()
})

/**
 * @summary Add a rule to a Role (requires rbac.roles.manage)
 */
export const postApiV1AdminRolesRoleIdRulesParams = zod.object({
  "roleId": zod.string().uuid()
})




export const postApiV1AdminRolesRoleIdRulesBody = zod.object({
  "rule": zod.string().min(1)
})

/**
 * @summary List the rules a Role currently has (requires rbac.roles.manage)
 */
export const getApiV1AdminRolesRoleIdRulesParams = zod.object({
  "roleId": zod.string().uuid()
})

export const getApiV1AdminRolesRoleIdRulesResponseItem = zod.string()
export const getApiV1AdminRolesRoleIdRulesResponse = zod.array(getApiV1AdminRolesRoleIdRulesResponseItem)

/**
 * @summary Remove a rule from a Role (requires rbac.roles.manage)
 */
export const deleteApiV1AdminRolesRoleIdRulesRuleParams = zod.object({
  "roleId": zod.string().uuid(),
  "rule": zod.string()
})

/**
 * @summary List the KNOWN_RULES catalog of every grantable rule (requires rbac.roles.manage)
 */
export const getApiV1AdminRulesResponseItem = zod.object({
  "rule": zod.string(),
  "description": zod.string()
})
export const getApiV1AdminRulesResponse = zod.array(getApiV1AdminRulesResponseItem)

/**
 * @summary List invite whitelist entries (requires admin.whitelist.manage)
 */
export const getApiV1AdminWhitelistResponseItem = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string().email(),
  "roleId": zod.string().uuid(),
  "createdBy": zod.string().uuid(),
  "createdAt": zod.string()
})
export const getApiV1AdminWhitelistResponse = zod.array(getApiV1AdminWhitelistResponseItem)

/**
 * @summary Add (or update) an invite whitelist entry (requires admin.whitelist.manage)
 */
export const postApiV1AdminWhitelistBody = zod.object({
  "email": zod.string().email(),
  "roleName": zod.enum(['Owner', 'SuperAdmin', 'Viewer'])
})

/**
 * @summary Remove an invite whitelist entry (requires admin.whitelist.manage)
 */
export const deleteApiV1AdminWhitelistEmailParams = zod.object({
  "email": zod.string().email()
})

